### ISSUE TITLE
How to Add Data to (Request/Response)Fields without validate.

### ISSUE THREAD

**Issue by qwerty2501** [mercari/go-httpdoc#17]
Sometimes add to Entry.RequestFields or Entry.ResponseFields without validate.   
eg: validation is difficult. Because the response body is randomly generated data.  
Then I tried as below and it is succeed.
```go
// record document before

document.Entries[len(document.Entries)-1].RequestFields = []httpdoc.Data{
	httpdoc.Data{Name: "login_id", Value: "sample_login_id", Description: "login id"},
	httpdoc.Data{Name: "password", Value: "sample_password", Description: "login password"},
}
```
Is this code right way?  
And Have you assumed that the user write like this?

**Comment by gong023** [comment]
Hello @qwerty2501, thank you for questioning.
I regret to say it's not good to handle Entry directly, although your code should work well. httpdoc is supposed to be used with validation always.

One of the solutions is to enable us to pass function via `httpdoc.RecordOption` and overwrite [defaultAssertFunc](https://github.com/mercari/go-httpdoc/blob/master/validate.go#L51). (Though this needs a pull request

**Comment by qwerty2501** [comment]
Thank you for answer.
After all  it's not good to handle Entry directly.
In my opinion, it is not good that overwrite assertFunc via httpdoc.RecordOption.
Because the user want to set assertFuncs for each field in request/response body.
And the user can't know which field from type of assertFunc.
like below
``` go
httpdoc.RecordOption{
    AssertFunc: func(t *testing.T, expected, actual interface{}, desc string){
       //How to know the target field?
   },
    WithValidate:func(validator *httpdoc.Validator) {
		validator.ResponseBody(t, []httpdoc.TestCase{
                       {"Token","xxxx-xxx-xxx","the Token"}, // This do not need validate. Because the token generation is depend on time.
                       {"UserID","sample_id","the user id"}, // This need validate. it should validate by defaultAssertFunc.
                }, &response)
   },
}
```
I guess it is better  set assertFunc to httpdoc.TestCase.
``` go
type TestCase struct {
	Target      string
	Expected    interface{}
	Description string
        AssertFunc: assertFunc // If nil, validate with defaultAssertFunc otherwise validate with TestCase.AssertFunc.
}
```
But as far as I can see, this way has a slightly bigger impact.
If you allow to set assertFunc to httpdoc.TestCase, I will PR.
Also, please let me know if there are other ideas.

**Comment by gong023** [comment]
> the user want to set assertFuncs for each field in request/response body

true. and I agree with your idea that adds AssertFunc in TestCase. It looks fair to have Target value, Expected value, and Assert function in one struct. In addition, it doesn't break compatibility of existing tests. We will review your PR if you send.
Appreciate for your contribution 😃

**Comment by qwerty2501** [comment]
OK. I will try.
Wait for few days.

**Comment by tcnksm** [comment]
This is fixed. Thanks
